name: complex
on: [pull_request, push]
jobs:
  build:
      runs-on: ubuntu-latest
      steps:
       - name: Python Syntax Checker
         uses: actions/checkout@v2
       - name: Python Syntax Checker
         uses: cclauss/Find-Python-syntax-errors-action@v0.2.0
            
          
